# Dockerfile.build
FROM openjdk:26-ea-oraclelinux8 AS build
WORKDIR /workspace

# Copy Maven wrapper + pom first to enable dependency caching
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw -q -B dependency:resolve

# Copy source and compile
COPY src ./src
RUN ./mvnw -q -B package -DskipTests

# Copy the JAR produced in the build image
COPY /workspace/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
